version: '3.7'
services:
  furious-nginx:
    build:
      context: ./docker
      dockerfile: dev/nginx/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8086:80"
    depends_on:
      - furious-php-fpm

  furious-php-fpm:
    build:
      context: ./docker
      dockerfile: dev/php-fpm/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - furious-postgres

  furious-php-cli:
    build:
      context: ./docker
      dockerfile: dev/php-cli/Dockerfile
    volumes:
      - ./:/app
      - composer:/root/.composer/cache
    depends_on:
      - furious-postgres
    working_dir: /app
    tty: true

  furious-postgres:
    image: postgres:11.2-alpine
    volumes:
      - furious-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "54321:5432"

volumes:
  composer:
  furious-postgres:
